/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'other' : IDL.Null,
  'entertainment' : IDL.Null,
  'food' : IDL.Null,
  'transport' : IDL.Null,
  'bills' : IDL.Null,
});
export const Person = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'personId' : IDL.Text,
  'category' : Category,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createExpense' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Int, Category],
      [IDL.Nat],
      [],
    ),
  'createPerson' : IDL.Func([IDL.Text], [Person], []),
  'deletePerson' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getPersonExpenses' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'listPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'updatePerson' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'entertainment' : IDL.Null,
    'food' : IDL.Null,
    'transport' : IDL.Null,
    'bills' : IDL.Null,
  });
  const Person = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'personId' : IDL.Text,
    'category' : Category,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'createExpense' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Int, Category],
        [IDL.Nat],
        [],
      ),
    'createPerson' : IDL.Func([IDL.Text], [Person], []),
    'deletePerson' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getPersonExpenses' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'listPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'updatePerson' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };