/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'other' : null } |
  { 'entertainment' : null } |
  { 'food' : null } |
  { 'transport' : null } |
  { 'bills' : null };
export interface Expense {
  'id' : bigint,
  'date' : bigint,
  'description' : string,
  'personId' : string,
  'category' : Category,
  'amount' : bigint,
}
export interface Person { 'id' : string, 'name' : string, 'createdAt' : bigint }
export interface _SERVICE {
  'createExpense' : ActorMethod<
    [string, bigint, string, bigint, Category],
    bigint
  >,
  'createPerson' : ActorMethod<[string], Person>,
  'deletePerson' : ActorMethod<[string], boolean>,
  'getPersonExpenses' : ActorMethod<
    [string, [] | [bigint], [] | [bigint]],
    Array<Expense>
  >,
  'listPeople' : ActorMethod<[], Array<Person>>,
  'updatePerson' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];